-- Script to check current foreign key constraints
-- Run this to see what constraints exist in your database

USE StudentSystemDB;

-- Check Enrollment table constraints
SELECT 
    CONSTRAINT_NAME,
    TABLE_NAME,
    COLUMN_NAME,
    REFERENCED_TABLE_NAME,
    REFERENCED_COLUMN_NAME,
    DELETE_RULE,
    UPDATE_RULE
FROM 
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE 
    TABLE_SCHEMA = 'StudentSystemDB' 
    AND TABLE_NAME = 'Enrollment'
    AND REFERENCED_TABLE_NAME IS NOT NULL;

-- Check Student table constraints
SELECT 
    CONSTRAINT_NAME,
    TABLE_NAME,
    COLUMN_NAME,
    REFERENCED_TABLE_NAME,
    REFERENCED_COLUMN_NAME,
    DELETE_RULE,
    UPDATE_RULE
FROM 
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE k
    JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS r 
        ON k.CONSTRAINT_NAME = r.CONSTRAINT_NAME
WHERE 
    k.TABLE_SCHEMA = 'StudentSystemDB' 
    AND k.TABLE_NAME = 'Student'
    AND k.REFERENCED_TABLE_NAME IS NOT NULL;

-- Check LecturerCourse table constraints
SELECT 
    CONSTRAINT_NAME,
    TABLE_NAME,
    COLUMN_NAME,
    REFERENCED_TABLE_NAME,
    REFERENCED_COLUMN_NAME,
    DELETE_RULE,
    UPDATE_RULE
FROM 
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE k
    JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS r 
        ON k.CONSTRAINT_NAME = r.CONSTRAINT_NAME
WHERE 
    k.TABLE_SCHEMA = 'StudentSystemDB' 
    AND k.TABLE_NAME = 'LecturerCourse'
    AND k.REFERENCED_TABLE_NAME IS NOT NULL;

